### PR TITLE
Change the card title number to an inline element

### PR DESCRIPTION
**Pull request by dmnd**
Before this change:

image

After this change:

image

### CODE REVIEW

**Comment by dewyze** [comment]
@dmnd I am not opposed to this change, but what is the reasoning? Just aesthetics?

**Comment by dmnd** [comment]
Information density is the main reason, along with aesthetics. Looking at it again now, the number could probably stand to have a little extra right margin too.

**Comment by dewyze** [comment]
@dmnd I am cool to merge this in. Do you want to add the padding to this PR or do it separately?

**Comment by dewyze** [comment]
@dmnd Just pinging to see if you want me to pull this in or wait for the margin.

**Comment by dmnd** [comment]
@dewyze I just added `margin-right: 10px`. Please pull & publish! Thanks for considering this. :smile:

**Comment by dewyze** [comment]
Hey @dmnd, can you rebase off of master and then I will pull this in today. Thanks!

**Comment by dmnd** [comment]
Done! Thanks.

**Comment by dewyze** [comment]
@dmnd Merged in. Although I think I am going to make a small tweak to fix the bigger gap between multi-line card titles. Since there are now two `<h2>` tags, it creates a bigger line height. If you would like to fix it feel free, otherwise I'll just tweak the css.

**Comment by dmnd** [comment]
I'm happy for you to tweak it yourself!

**Pull request merged**
